//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chap02.EntityFramework.Obj2_2.DataProvider.EntityConnection1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int Detailid { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string Vendor { get; set; }
        public string ItemDescription { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
