//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chap02.EntityFramework.Obj2_2.DataProvider.EntityDataReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int CustomerId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
